### ISSUE TITLE
java.lang.IllegalArgumentException: Document base /var/lib/tomcat6/webapps/solr-4.8.1 does not exist or is not a readable directory

### ISSUE THREAD

**Issue by jrenggli** [obi12341/solr-typo3#1]
Both the image on https://hub.docker.com/r/writl/solr-typo3/ and my own build of this repository aren't working currently. I always get the following error message

```
SEVERE: Cannot find specified temporary folder at /tmp/tomcat6-tomcat6-tmp
Aug 11, 2015 7:24:09 AM org.apache.catalina.startup.HostConfig deployDescriptor
WARNING: A docBase /var/lib/tomcat6/webapps/solr-4.8.1.war inside the host appBase has been specified, and will be ignored
Aug 11, 2015 7:24:09 AM org.apache.catalina.core.StandardContext resourcesStart
SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Document base /var/lib/tomcat6/webapps/solr-4.8.1 does not exist or is not a readable directory
    at org.apache.naming.resources.FileDirContext.setDocBase(FileDirContext.java:142)
    at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4324)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4493)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
    at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
    at org.apache.catalina.core.StandardService.start(StandardService.java:525)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

Aug 11, 2015 7:24:09 AM org.apache.catalina.core.StandardContext start
SEVERE: Error in resourceStart()
Aug 11, 2015 7:24:09 AM org.apache.catalina.core.StandardContext start
SEVERE: Error getConfigured
Aug 11, 2015 7:24:09 AM org.apache.catalina.core.StandardContext start
SEVERE: Context [/solr-4.8.1] startup failed due to previous errors
```

A previous version I use 9 months ago worked tough.

**Comment by obi12341** [comment]
Thanks for your report. I will take a look into it.

Edit: DKD removed solr from the mirror. https://github.com/TYPO3-Solr/ext-solr/issues/49
