### ISSUE TITLE
Extracting content with Tika fails due to missing tmp directory

### ISSUE THREAD

**Issue by lorenzulrich** [obi12341/solr-typo3#2]
If the Solr server is used to extract content from documents (using Tika), the file is sent from the solrfal extension to Solr. It needs to be saved in a temporary directory that doesn't exist.

From the error log:

```
14.8.2015, 17:27:37
ERROR
SolrDispatchFilter
null:org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /tmp/tomcat6-tomcat6-tmp/upload_20d9dfa2_14f2cd06fb2__8000_00000079.tmp (No such file or directory)
null:org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /tmp/tomcat6-tomcat6-tmp/upload_20d9dfa2_14f2cd06fb2__8000_00000079.tmp (No such file or directory)
    at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:367)
    at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
    at org.apache.solr.servlet.SolrRequestParsers$MultipartRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:543)
    at org.apache.solr.servlet.SolrRequestParsers$StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:679)
    at org.apache.solr.servlet.SolrRequestParsers.parse(SolrRequestParsers.java:146)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:398)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /tmp/tomcat6-tomcat6-tmp/upload_20d9dfa2_14f2cd06fb2__8000_00000079.tmp (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:181)
    at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:226)
    at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:130)
    at org.apache.commons.fileupload.util.Streams.copy(Streams.java:101)
    at org.apache.commons.fileupload.util.Streams.copy(Streams.java:64)
    at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:362)
    ... 18 more
```

**Comment by obi12341** [comment]
could you try it again with the newest version?
Can not test it here.

**Comment by lorenzulrich** [comment]
It works, thanks!

**Comment by obi12341** [comment]
Okay :) New bugfix-release is on its way :)

**Comment by lorenzulrich** [comment]
Thanks - great work!
